<?php

/*
 * Copyright Matthew Asham and BinktermPHP Contributors
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
 */

namespace BinktermPHP\AreaFix;

use BinktermPHP\Config;
use BinktermPHP\Binkp\Logger;

/**
 * Structural parser for AreaFix and FileFix response messages from FTN hub mailers.
 *
 * Recognizes concrete syntactic structures generated by major hub software:
 * - Mystic BBS & MBSE Command/Result blocks (direct actions, stacked requests, indented lists)
 * - Delimited tables (Husky, Clearing Houz, FastEcho, FrontDoor, InterMail)
 * - Columnar and dotted-leader tables (HPT, Husky)
 * - Quoted-address lists (BBBS/Li6: "+TAG (addr) \"description\"", with wrapped
 *   multi-line descriptions and combined echo+file area sections)
 *
 * By relying on structural grammar rather than keyword blocklisting, real areas
 * with common names (such as LINUX, BASE, WINDOWS) are preserved, while help
 * manuals and freeform prose are never misidentified as area lists.
 *
 * As a last resort, when none of the above grammars match, a conservative
 * freeform "TAG   Description" line matcher is tried (see parseFreeformList()).
 * It is gated by the same strict isValidTag() check as every other grammar
 * rather than a keyword blocklist, never marks a row as subscribed, and logs
 * whenever it is the tier that produced a result, so an unrecognized hub
 * format can be turned into a proper structural grammar over time instead of
 * silently failing forever.
 */
class AreaFixParser
{
    public const ACTION_SUBSCRIBE = 'subscribe';
    public const ACTION_UNSUBSCRIBE = 'unsubscribe';
    public const ACTION_AVAILABLE = 'available';

    private const VALID_ACTIONS = [self::ACTION_SUBSCRIBE, self::ACTION_UNSUBSCRIBE, self::ACTION_AVAILABLE];

    /**
     * Stable tier identifiers, used by per-uplink grammar memory (see
     * AreaFixManager) to remember which tier last matched a given uplink and
     * to try it first on the next reply. A data-driven grammar's tier name is
     * "configured:<grammar id>" rather than a fixed constant.
     */
    public const TIER_MYSTIC_BLOCKS = 'mystic_blocks';
    public const TIER_DELIMITED_TABLE = 'delimited_table';
    public const TIER_COLUMNAR_TABLE = 'columnar_table';
    public const TIER_QUOTED_ADDRESS_LIST = 'quoted_address_list';
    public const TIER_FLAGGED_DOTTED_QUOTED_LIST = 'flagged_dotted_quoted_list';
    public const TIER_FREEFORM = 'freeform';
    private const CONFIGURED_TIER_PREFIX = 'configured:';

    /** @var array<int, array<string, mixed>>|null */
    private ?array $configuredGrammarsCache = null;

    private Logger $logger;

    public function __construct()
    {
        $this->logger = new Logger(Config::getLogPath('server.log'), Logger::LEVEL_INFO, false);
    }

    /**
     * Parse AreaFix or FileFix response body into structured area items.
     *
     * @param string $body Raw message body text
     * @param string|null $subject Optional message subject for context
     * @return array<int, array{
     *     name: string,
     *     description: ?string,
     *     action: string,
     *     is_subscribed: bool
     * }>
     */
    public function parse(string $body, ?string $subject = null, ?string $preferredTier = null): array
    {
        return $this->parseWithTier($body, $subject, $preferredTier)['areas'];
    }

    /**
     * Same as parse(), but also reports which tier produced the result, so a
     * caller (AreaFixManager) can remember it per-uplink and notice when a
     * hub's format changes between replies (see PR460Proposal Improvement 6).
     *
     * Tries each tier in its normal order (the five built-in structural
     * grammars, then data-driven configured grammars in config file order,
     * then the freeform fallback), except that $preferredTier — when given and
     * still present in the tier list — is tried first. This is a pure
     * reordering: it never changes which tier ultimately wins for a given
     * body, only how quickly it's found when the hint is correct.
     *
     * @param string $body Raw message body text
     * @param string|null $subject Optional message subject for context
     * @param string|null $preferredTier A tier identifier (one of the TIER_* constants,
     *     or "configured:<grammar id>") to try before the normal order
     * @return array{
     *     areas: array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>,
     *     tier: ?string
     * }
     */
    public function parseWithTier(string $body, ?string $subject = null, ?string $preferredTier = null): array
    {
        $body = str_replace(["\r\n", "\r"], "\n", $body);
        $tiers = $this->buildTierList($body);

        if ($preferredTier !== null) {
            $index = null;
            foreach ($tiers as $i => $tier) {
                if ($tier['name'] === $preferredTier) {
                    $index = $i;
                    break;
                }
            }
            if ($index !== null) {
                $preferred = $tiers[$index];
                unset($tiers[$index]);
                array_unshift($tiers, $preferred);
            }
        }

        foreach ($tiers as $tier) {
            $areas = ($tier['match'])();
            if ($areas === null || empty($areas)) {
                continue;
            }

            if ($tier['name'] === self::TIER_FREEFORM) {
                $this->logger->info('AreaFixParser: no structural grammar matched, used freeform fallback', [
                    'areas_found'  => count($areas),
                    'body_excerpt' => substr($body, 0, 200),
                ]);
            } elseif (str_starts_with($tier['name'], self::CONFIGURED_TIER_PREFIX)) {
                $this->logger->info('AreaFixParser: matched data-driven grammar', [
                    'grammar_id'  => substr($tier['name'], strlen(self::CONFIGURED_TIER_PREFIX)),
                    'areas_found' => count($areas),
                ]);
            }

            return ['areas' => $this->deduplicateAreas($areas), 'tier' => $tier['name']];
        }

        return ['areas' => [], 'tier' => null];
    }

    /**
     * Build the ordered list of tiers to try against a message body: the five
     * built-in structural grammars, then any data-driven grammars from
     * config/areafix_grammars.json (or its .example fallback) in file order,
     * then the freeform fallback.
     *
     * @return array<int, array{name: string, match: callable(): ?array}>
     */
    private function buildTierList(string $body): array
    {
        $tiers = [
            ['name' => self::TIER_MYSTIC_BLOCKS, 'match' => fn() => $this->parseMysticBlocks($body)],
            ['name' => self::TIER_DELIMITED_TABLE, 'match' => fn() => $this->parseDelimitedTable($body)],
            ['name' => self::TIER_COLUMNAR_TABLE, 'match' => fn() => $this->parseColumnarTable($body)],
            ['name' => self::TIER_QUOTED_ADDRESS_LIST, 'match' => fn() => $this->parseQuotedAddressList($body)],
            ['name' => self::TIER_FLAGGED_DOTTED_QUOTED_LIST, 'match' => fn() => $this->parseFlaggedDottedQuotedList($body)],
        ];

        foreach ($this->loadConfiguredGrammars() as $grammar) {
            $tierName = self::CONFIGURED_TIER_PREFIX . (string)($grammar['id'] ?? '');
            $tiers[] = ['name' => $tierName, 'match' => fn() => $this->matchConfiguredGrammar($grammar, $body)];
        }

        $tiers[] = ['name' => self::TIER_FREEFORM, 'match' => fn() => $this->parseFreeformList($body)];

        return $tiers;
    }

    /**
     * Check whether message body contains actionable AreaFix area data
     * (subscriptions, unsubscriptions, or valid area lists).
     *
     * Returns false for help manuals, empty rescan receipts, and error notifications.
     */
    public function hasActionableContent(string $body, ?string $subject = null): bool
    {
        $areas = $this->parse($body, $subject);
        return !empty($areas);
    }

    /**
     * Parse Mystic BBS and MBSE Command / Result blocks.
     *
     * Matches patterns:
     *   Command: +TAG [R=100]
     *    Result: Echo will now be exported
     *
     *   Command: -TAG
     *    Result: Echo will no longer be exported
     *
     *   Command: %LINKED (or %QUERY, %LIST, %UNLINKED)
     *    Result: List of all linked areas:
     *     TAG1                                Description 1
     *     TAG2                                Description 2
     *
     * %QUERY in particular can list both linked and unlinked areas in one
     * block; a row annotated "(linked)"/"(unlinked)"/"(not linked)" is
     * classified by that annotation rather than by the command name.
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseMysticBlocks(string $body): ?array
    {
        if (!preg_match('/^Command:\s*/m', $body)) {
            return null;
        }

        $lines = explode("\n", $body);
        $areas = [];
        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = $lines[$i];

            // Stop command parsing once a help manual banner is reached
            if (preg_match('/^[\.\+\s]*-{3,}.*Help/i', $line) || preg_match('/^\|\s*.*(?:AreaFix|FileFix)\s+Help\s*\|/i', $line)) {
                break;
            }

            // Real Mystic command lines start flush at column 0 (not indented inside tutorial examples)
            if (!preg_match('/^Command:\s*(.+)$/i', $line, $cmdMatch)) {
                continue;
            }

            $commandRaw = trim($cmdMatch[1]);

            // Find subsequent Result: line (within next 3 lines)
            $resultRaw = null;
            $resultLineIndex = -1;
            for ($j = $i + 1; $j < min($i + 4, $totalLines); $j++) {
                if (preg_match('/^Result:\s*(.*)$/i', trim($lines[$j]), $resMatch)) {
                    $resultRaw = trim($resMatch[1]);
                    $resultLineIndex = $j;
                    break;
                }
            }

            if ($resultRaw === null) {
                continue;
            }

            // A) Direct subscription command: +TAG [params]
            if (preg_match('/^\+\s*([A-Za-z0-9_\-\.]+)(?:\s+\[[^\]]*\])?$/', $commandRaw, $tagMatch)) {
                $tag = strtoupper($tagMatch[1]);
                if (self::isValidTag($tag)) {
                    // Check if result indicates success
                    if (preg_match('/(?:will now be exported|linked|added|subscribed|now connected|echo linked)/i', $resultRaw)) {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => self::ACTION_SUBSCRIBE,
                            'is_subscribed' => true,
                        ];
                    }
                }
                $i = $resultLineIndex;
                continue;
            }

            // B) Direct unsubscription command: -TAG [params]
            if (preg_match('/^\-\s*([A-Za-z0-9_\-\.]+)(?:\s+\[[^\]]*\])?$/', $commandRaw, $tagMatch)) {
                $tag = strtoupper($tagMatch[1]);
                if (self::isValidTag($tag)) {
                    if (preg_match('/(?:will no longer be exported|unlinked|removed|unsubscribed|disconnected)/i', $resultRaw)) {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => self::ACTION_UNSUBSCRIBE,
                            'is_subscribed' => false,
                        ];
                    }
                }
                $i = $resultLineIndex;
                continue;
            }

            // C) List commands: %LINKED, %QUERY, %LIST, %UNLINKED, %AVAIL
            if (preg_match('/^%([A-Za-z0-9_\-]+)\b/i', $commandRaw, $pctMatch)) {
                $cmdName = strtoupper($pctMatch[1]);
                $isLinkedCmd   = in_array($cmdName, ['LINKED', 'QUERY', 'LINK'], true);
                $isUnlinkedCmd = in_array($cmdName, ['UNLINKED'], true);
                $isListCmd     = in_array($cmdName, ['LIST', 'AVAIL'], true);

                if (($isLinkedCmd || $isUnlinkedCmd || $isListCmd) && preg_match('/list of/i', $resultRaw)) {
                    // Indented lines immediately follow the Result: line
                    $k = $resultLineIndex + 1;
                    while ($k < $totalLines) {
                        $dataLine = $lines[$k];
                        $dataTrim = trim($dataLine);

                        // Stop if we hit a new command or a non-indented decorative section
                        if (preg_match('/^Command:\s*/i', $dataTrim) || preg_match('/^[.\-+=\*]{3,}/', $dataTrim)) {
                            break;
                        }

                        // An indented data row starts with 2+ spaces or a tab
                        if (preg_match('/^(?:[ ]{2,}|\t+)([A-Za-z0-9_\-\.]+)(?:\s{2,}|\t+)(.*)$/', $dataLine, $rowMatch)) {
                            $tag = strtoupper(trim($rowMatch[1]));
                            $desc = trim($rowMatch[2]);
                            if (self::isValidTag($tag)) {
                                // A command like %QUERY can list both linked and
                                // unlinked areas in one block. If this specific row
                                // carries its own "(linked)"/"(unlinked)" annotation,
                                // trust that over the command-level default; otherwise
                                // fall back to the command default (correct for a
                                // %LINKED-only listing, where every row is linked by
                                // definition).
                                $rowIsLinked = $isLinkedCmd;
                                if (preg_match('/\(\s*(?:not\s+linked|unlinked)\s*\)\s*$/i', $desc)) {
                                    $rowIsLinked = false;
                                    $desc = trim(preg_replace('/\(\s*(?:not\s+linked|unlinked)\s*\)\s*$/i', '', $desc));
                                } elseif (preg_match('/\(\s*linked\s*\)\s*$/i', $desc)) {
                                    $rowIsLinked = true;
                                    $desc = trim(preg_replace('/\(\s*linked\s*\)\s*$/i', '', $desc));
                                }

                                $action = $rowIsLinked ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE;
                                $areas[] = [
                                    'name'          => $tag,
                                    'description'   => $desc !== '' ? $desc : null,
                                    'action'        => $action,
                                    'is_subscribed' => $rowIsLinked,
                                ];
                            }
                        } elseif ($dataTrim !== '' && !preg_match('/^[ ]{2,}|\t+/', $dataLine)) {
                            // Non-indented non-empty line ends the listing block
                            break;
                        }

                        $k++;
                    }
                    $i = $k - 1;
                    continue;
                }
            }

            // Advance past the result line
            $i = $resultLineIndex;
        }

        return $areas;
    }

    /**
     * Parse delimited tables (colon ':' or pipe '|').
     *
     * Matches patterns:
     *   :---:------------:--------------------------------------------------:------:
     *   :   : AREA       : DESCRIPTION                                      : MSGS :
     *   :---:------------:--------------------------------------------------:------:
     *   :*  : FSX_ADS    : FSX: Ads + ANSI Art                              :  547 :
     *   :   : FSX_BBS    : FSX: BBS Support/Dev                             :   53 :
     *
     * Or pipe tables:
     *   | AREA | DESCRIPTION |
     *   | FSX_ADS | FSX: Ads + ANSI Art |
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseDelimitedTable(string $body): ?array
    {
        $lines = explode("\n", $body);
        $headerFound = false;
        $delimiter = null;
        $tagCol = -1;
        $descCol = -1;
        $statusCol = -1;
        $areas = [];

        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = trim($lines[$i]);
            if ($line === '') {
                if ($headerFound && !empty($areas)) {
                    // Blank line after table rows concludes the table
                    break;
                }
                continue;
            }

            // Look for table header if not found yet
            if (!$headerFound) {
                // Must contain AREA/ECHOTAG and DESCRIPTION/STATUS/MSGS/FILES
                if (preg_match('/[:|]\s*(?:AREA|ECHOTAG|TAG)\s*[:|]/i', $line)) {
                    $delimiter = str_contains($line, ':') ? ':' : '|';
                    $cols = array_map('trim', explode($delimiter, $line));

                    // Remove empty outside elements from boundary delimiters
                    if (isset($cols[0]) && $cols[0] === '') {
                        array_shift($cols);
                    }
                    if (!empty($cols) && end($cols) === '') {
                        array_pop($cols);
                    }

                    foreach ($cols as $idx => $colName) {
                        $colUpper = strtoupper($colName);
                        if (in_array($colUpper, ['AREA', 'ECHOTAG', 'TAG'], true)) {
                            $tagCol = $idx;
                        } elseif (in_array($colUpper, ['DESCRIPTION', 'DESC'], true)) {
                            $descCol = $idx;
                        } elseif ($idx === 0 && ($colUpper === '' || in_array($colUpper, ['STATUS', 'ST', 'FLAGS'], true))) {
                            $statusCol = $idx;
                        }
                    }

                    if ($tagCol >= 0) {
                        $headerFound = true;
                    }
                }
                continue;
            }

            // Once header is found, parse table rows
            // Skip decorative separator lines (:---:---:, |---|---|)
            if (preg_match('/^[:|\s]*[-=*#~:\s]{3,}[:|\s]*$/', $line)) {
                continue;
            }

            // Data line must start with or contain the delimiter
            if (!str_contains($line, $delimiter)) {
                if (!empty($areas)) {
                    break; // End of table
                }
                continue;
            }

            $rawCols = explode($delimiter, $line);
            if (isset($rawCols[0]) && trim($rawCols[0]) === '') {
                array_shift($rawCols);
            }
            if (!empty($rawCols) && trim(end($rawCols)) === '') {
                array_pop($rawCols);
            }

            if (isset($rawCols[$tagCol])) {
                $tag = strtoupper(trim($rawCols[$tagCol]));
                if (self::isValidTag($tag)) {
                    $desc = null;
                    if ($descCol >= 0 && isset($rawCols[$descCol])) {
                        $hasTrailingCol = count($cols) > ($descCol + 1);
                        if ($hasTrailingCol && count($rawCols) > ($descCol + 1)) {
                            $numTrailing = count($cols) - 1 - $descCol;
                            $sliceLen = max(1, count($rawCols) - $descCol - $numTrailing);
                            $descParts = array_slice($rawCols, $descCol, $sliceLen);
                            $desc = trim(implode($delimiter, $descParts));
                        } else {
                            $descParts = array_slice($rawCols, $descCol);
                            $desc = trim(implode($delimiter, $descParts));
                        }
                    }

                    // Discard description if it contains ANSI box drawing / block art
                    if ($desc !== null && (preg_match('/[▄█▀▌▐░▒▓─│┌┐└┘├┤┬┴┼═║]/u', $desc) || preg_match('/[\xB0-\xDF]/', $desc))) {
                        $desc = null;
                    }

                    $status = ($statusCol >= 0 && isset($rawCols[$statusCol])) ? trim($rawCols[$statusCol]) : '';

                    $isSubscribed = str_contains($status, '*') || str_contains($status, '+');
                    $action = $isSubscribed ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE;

                    $areas[] = [
                        'name'          => $tag,
                        'description'   => ($desc !== null && $desc !== '') ? $desc : null,
                        'action'        => $action,
                        'is_subscribed' => $isSubscribed,
                    ];
                }
            }
        }

        return $headerFound ? $areas : null;
    }

    /**
     * Parse columnar fixed-width or dotted-leader tables (HPT, Husky, FastEcho).
     *
     * Matches patterns:
     *   Area                                                Status
     *   --------------------------------------------------  -------------------------
     *   LVLY_ANNOUNCE ....................................  rescanned 22 mails
     *   LVLY_BINKTERMPHP .................................  subscribed
     *
     * Or:
     *   Area                                                Description
     *   --------------------------------------------------  -------------------------
     *   SYS_GEN                                             SysOp General Chat
     *
     * Also matches headers where the tag column isn't literally named "Area" but
     * contains it as a whole word (e.g. AreaMgr-style "Con  Message area  Description"),
     * as long as a dashed separator line immediately follows.
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseColumnarTable(string $body): ?array
    {
        $lines = explode("\n", $body);
        $headerFound = false;
        $isStatusTable = false;
        $areas = [];

        $totalLines = count($lines);

        for ($i = 0; $i < $totalLines; $i++) {
            $line = trim($lines[$i]);

            if (!$headerFound) {
                // Look for an "area" column (as a whole word, anywhere in the header)
                // followed later by "Status", "Description", "Msgs", or "Files"
                if (preg_match('/\barea\b.*?\b(Status|Description|Msgs|Files)\b/i', $line, $hMatch)) {
                    // Check if next line is a dash separator
                    if (isset($lines[$i + 1]) && preg_match('/^[-=]{3,}\s+[-=]{3,}/', trim($lines[$i + 1]))) {
                        $headerFound = true;
                        $isStatusTable = (strcasecmp($hMatch[1], 'Status') === 0);
                        $i++; // skip separator line
                        continue;
                    }
                }
                continue;
            }

            // End of table boundaries
            if ($line === '' || str_starts_with($line, '---') || str_starts_with($line, '* Origin:') || str_contains($line, 'Following is the original message text')) {
                if (!empty($areas)) {
                    break;
                }
                continue;
            }

            // Parse dotted-leader line: TAG ........ Status or Description
            if (preg_match('/^([A-Za-z0-9_\-\.]+)\s+\.{3,}\s*(.*)$/', $line, $rowMatch)) {
                $tag = strtoupper(trim($rowMatch[1]));
                $colValue = trim($rowMatch[2]);

                if (self::isValidTag($tag)) {
                    if ($isStatusTable) {
                        $action = self::ACTION_AVAILABLE;
                        $isSubscribed = false;

                        if (preg_match('/\b(?:unsubscribed|removed)\b/i', $colValue)) {
                            $action = self::ACTION_UNSUBSCRIBE;
                            $isSubscribed = false;
                        } elseif (preg_match('/\b(?:already\s+subscribed|subscribed|rescanned\s+\d+)\b/i', $colValue)) {
                            $action = self::ACTION_SUBSCRIBE;
                            $isSubscribed = true;
                        }

                        $areas[] = [
                            'name'          => $tag,
                            'description'   => null,
                            'action'        => $action,
                            'is_subscribed' => $isSubscribed,
                        ];
                    } else {
                        $areas[] = [
                            'name'          => $tag,
                            'description'   => $colValue !== '' ? $colValue : null,
                            'action'        => self::ACTION_AVAILABLE,
                            'is_subscribed' => false,
                        ];
                    }
                }
                continue;
            }

            // Parse standard two-column line: TAG   Description
            if (preg_match('/^([A-Za-z0-9_\-\.]+)\s{3,}(.*)$/', $line, $rowMatch)) {
                $tag = strtoupper(trim($rowMatch[1]));
                $colValue = trim($rowMatch[2]);

                if (self::isValidTag($tag)) {
                    $areas[] = [
                        'name'          => $tag,
                        'description'   => $colValue !== '' ? $colValue : null,
                        'action'        => self::ACTION_AVAILABLE,
                        'is_subscribed' => false,
                    ];
                }
            }
        }

        return $headerFound ? $areas : null;
    }

    /**
     * Parse BBBS/Li6-style quoted-address lists.
     *
     * Matches patterns:
     *   List of all echo areas available for node 1:153/150.0.
     *   + = Area already connected
     *
     *   +10TH_AMD                       (1:153/757) "10th Amendment Discussion"
     *    ABLED                          (1:153/757) "disABLED Users Information
     *                                   Exchange"
     *
     * A leading "+" marks a subscribed/connected area; a leading space marks one
     * that is merely available. Descriptions may wrap onto continuation lines
     * with no tag of their own, terminated by the closing quote. The same
     * grammar also covers a file-area list in the same reply (address may carry
     * a ", NkB" size suffix), including reuse of a tag between the echo-area and
     * file-area sections with different descriptions (deduplicateAreas() keeps
     * whichever description and action wins by its normal precedence rules).
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseQuotedAddressList(string $body): ?array
    {
        $lines = explode("\n", $body);
        $totalLines = count($lines);
        $areas = [];
        $found = false;

        for ($i = 0; $i < $totalLines; $i++) {
            $line = $lines[$i];

            if (!preg_match('/^[+ ]([A-Za-z0-9_\-.]+)\s+\([^)]*\)\s+"(.*)$/', $line, $m)) {
                continue;
            }

            $tag = strtoupper(trim($m[1]));
            if (!self::isValidTag($tag)) {
                continue;
            }

            $found = true;
            $isSubscribed = ($line[0] === '+');

            // Collect wrapped continuation lines until the closing quote appears,
            // stopping early if the next line is itself a new entry, a blank
            // line, or a banner/tearline (defends against ever merging entries).
            $descParts = [$m[2]];
            $j = $i;
            while (!str_ends_with(rtrim(end($descParts)), '"') && ($j + 1) < $totalLines) {
                $nextLine = $lines[$j + 1];
                $nextTrimmed = trim($nextLine);
                if ($nextTrimmed === ''
                    || preg_match('/^[+ ][A-Za-z0-9_\-.]+\s+\([^)]*\)\s+"/', $nextLine)
                    || preg_match('/^-{2,}\s/', $nextTrimmed)
                    || stripos($nextTrimmed, 'List of all') !== false) {
                    break;
                }
                $j++;
                $descParts[] = $nextTrimmed;
            }
            $i = $j;

            $desc = trim(rtrim(trim(implode(' ', $descParts)), '"'));

            $areas[] = [
                'name'          => $tag,
                'description'   => $desc !== '' ? $desc : null,
                'action'        => $isSubscribed ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE,
                'is_subscribed' => $isSubscribed,
            ];
        }

        return $found ? $areas : null;
    }

    /**
     * Parse HPT-style flag-prefixed dotted-leader lists with quoted descriptions.
     *
     * Matches patterns:
     *   Available areas for 227:1/400
     *
     *   *S   LVLY_ADULT ............... "Mature/18+ topics of discussion, etc."
     *   *S   LVLY_COLDWARCOMMS ............................................... "Coldwar
     *                               Communications with an emphasis on AT&T Longlines"
     *
     *   '*' = area is active
     *   'R' = area is readonly for you
     *
     * The leading 0-2 character flag field (any combination of '*', 'R', 'W',
     * 'M', 'S') indicates linked/subscribed state; '*' present means the area
     * is currently linked. Descriptions may wrap onto an unindented-tag
     * continuation line, terminated by the closing quote. The area block ends
     * at the first blank line, before the "'X' = ..." flag legend.
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function parseFlaggedDottedQuotedList(string $body): ?array
    {
        $lines = explode("\n", $body);
        $totalLines = count($lines);
        $areas = [];
        $found = false;

        for ($i = 0; $i < $totalLines; $i++) {
            $line = $lines[$i];

            if (trim($line) === '') {
                if ($found) {
                    // Blank line after at least one matched row ends the list
                    // (the flag legend and summary text follow).
                    break;
                }
                continue;
            }

            if (!preg_match('/^([*RWMS]*)\s+([A-Za-z0-9_\-.]+)\s+\.{3,}\s*"(.*)$/', $line, $m)) {
                continue;
            }

            $tag = strtoupper(trim($m[2]));
            if (!self::isValidTag($tag)) {
                continue;
            }

            $found = true;
            $isSubscribed = str_contains($m[1], '*');

            // Collect wrapped continuation lines until the closing quote appears,
            // stopping early if the next line is itself a new entry, blank, or
            // the start of the flag legend (defends against merging entries).
            $descParts = [$m[3]];
            $j = $i;
            while (!str_ends_with(rtrim(end($descParts)), '"') && ($j + 1) < $totalLines) {
                $nextLine = $lines[$j + 1];
                $nextTrimmed = trim($nextLine);
                if ($nextTrimmed === ''
                    || preg_match('/^[*RWMS]*\s+[A-Za-z0-9_\-.]+\s+\.{3,}\s*"/', $nextLine)
                    || str_starts_with($nextTrimmed, "'")) {
                    break;
                }
                $j++;
                $descParts[] = $nextTrimmed;
            }
            $i = $j;

            $desc = trim(rtrim(trim(implode(' ', $descParts)), '"'));

            $areas[] = [
                'name'          => $tag,
                'description'   => $desc !== '' ? $desc : null,
                'action'        => $isSubscribed ? self::ACTION_SUBSCRIBE : self::ACTION_AVAILABLE,
                'is_subscribed' => $isSubscribed,
            ];
        }

        return $found ? $areas : null;
    }

    /**
     * Last-resort conservative freeform line matcher for hub formats with no
     * recognizable header, banner, or delimiter at all (e.g. a bare SBBSecho
     * "TAG   Description" list terminated only by a "--- <mailer>" tearline).
     *
     * Gated by the same strict isValidTag() check as every other grammar rather
     * than a keyword blocklist. Rows found here are never marked as subscribed
     * (always ACTION_AVAILABLE) since there is no structural signal to confirm
     * a subscription — only a sysop confirming the mandatory sync preview can
     * turn one into an active subscription.
     *
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>
     */
    private function parseFreeformList(string $body): array
    {
        $lines = explode("\n", $body);
        $areas = [];

        foreach ($lines as $line) {
            $trimmed = trim($line);
            if ($trimmed === '') {
                continue;
            }

            // Tearlines, origin lines, kludges, and decorative separators are never area rows
            if (preg_match('/^-{2,}\s/', $trimmed)
                || str_starts_with($trimmed, '* Origin:')
                || str_starts_with($trimmed, '...')
                || preg_match('/^(?:to|from|subject|date|cost|flags|origin|dest|intl|replyaddr|msgid|chrs|pid|tzutc)\s*[:\s]/i', $trimmed)
                || preg_match('/^[:|\s]*[-=*#~:\s]{3,}[:|\s]*$/', $trimmed)) {
                continue;
            }

            // Bare "TAG   Description" line: tag, then 2+ spaces or a tab, then description
            if (!preg_match('/^([A-Za-z0-9_\-.]+)(?:[ ]{2,}|\t+)(.+)$/', $trimmed, $m)) {
                continue;
            }

            $tag = strtoupper(trim($m[1]));
            if (!self::isValidTag($tag)) {
                continue;
            }

            $desc = trim($m[2]);
            if ($desc !== '' && (preg_match('/[▄█▀▌▐░▒▓─│┌┐└┘├┤┬┴┼═║]/u', $desc) || preg_match('/[\xB0-\xDF]/', $desc))) {
                $desc = null;
            }

            $areas[] = [
                'name'          => $tag,
                'description'   => ($desc !== null && $desc !== '') ? $desc : null,
                'action'        => self::ACTION_AVAILABLE,
                'is_subscribed' => false,
            ];
        }

        return $areas;
    }

    /**
     * Inject an explicit set of data-driven grammar definitions to use
     * instead of loading config/areafix_grammars.json, bypassing the file
     * entirely for the lifetime of this instance.
     *
     * Used by the admin "test against a sample" feature to run the exact
     * grammar definitions currently in the editor (which may not have been
     * saved yet) through the real parsing pipeline — built-in grammars still
     * run first, then these, then the freeform fallback, exactly as
     * parseWithTier() always tries them — without ever writing to
     * config/areafix_grammars.json.
     *
     * @param array<int, array<string, mixed>> $grammars
     */
    public function setConfiguredGrammarsOverride(array $grammars): void
    {
        $this->configuredGrammarsCache = array_values(array_filter($grammars, 'is_array'));
    }

    /**
     * Load data-driven grammar definitions from config/areafix_grammars.json.
     *
     * The file is optional; a missing file, empty array, or invalid JSON all
     * result in no configured grammars (built-in grammars and the freeform
     * fallback are unaffected). Cached per-process since this is invoked once
     * per parse() call and the file only changes via the admin daemon.
     *
     * If config/areafix_grammars.json doesn't exist yet, falls back to the
     * shipped config/areafix_grammars.json.example so its (disabled-by-default)
     * sample grammar is available as a starting point without requiring a
     * sysop to create the real file first. The example ships with every
     * grammar disabled, so this fallback never changes parsing behavior on
     * its own.
     *
     * @return array<int, array<string, mixed>>
     */
    private function loadConfiguredGrammars(): array
    {
        if ($this->configuredGrammarsCache !== null) {
            return $this->configuredGrammarsCache;
        }

        $path = __DIR__ . '/../../config/areafix_grammars.json';
        if (!file_exists($path)) {
            $path = __DIR__ . '/../../config/areafix_grammars.json.example';
        }
        if (!file_exists($path)) {
            return $this->configuredGrammarsCache = [];
        }

        $json = file_get_contents($path);
        if ($json === false) {
            return $this->configuredGrammarsCache = [];
        }

        $decoded = json_decode($json, true);
        if (json_last_error() !== JSON_ERROR_NONE || !is_array($decoded)) {
            $this->logger->warning('AreaFixParser: config/areafix_grammars.json is invalid JSON, ignoring', [
                'json_error' => json_last_error_msg(),
            ]);
            return $this->configuredGrammarsCache = [];
        }

        return $this->configuredGrammarsCache = array_values(array_filter($decoded, 'is_array'));
    }

    /**
     * List every tier identifier parse()/parseWithTier() could currently
     * report, in the same order they're tried: the five built-in structural
     * grammars, then "configured:<id>" for each data-driven grammar
     * currently defined (regardless of its own enabled flag), then the
     * freeform fallback. Used by the admin UI (per-uplink grammar memory
     * editor) to populate a "force this tier" selector without accepting
     * arbitrary strings into areafix_grammar_memory.
     *
     * @return array<int, string>
     */
    public function getKnownTierIds(): array
    {
        $tiers = [
            self::TIER_MYSTIC_BLOCKS,
            self::TIER_DELIMITED_TABLE,
            self::TIER_COLUMNAR_TABLE,
            self::TIER_QUOTED_ADDRESS_LIST,
            self::TIER_FLAGGED_DOTTED_QUOTED_LIST,
        ];

        foreach ($this->loadConfiguredGrammars() as $grammar) {
            $id = (string)($grammar['id'] ?? '');
            if ($id !== '') {
                $tiers[] = self::CONFIGURED_TIER_PREFIX . $id;
            }
        }

        $tiers[] = self::TIER_FREEFORM;

        return $tiers;
    }

    /**
     * Attempt to match a single data-driven grammar definition against the
     * message body.
     *
     * Grammar schema (see docs/AreaFix.md for the full reference):
     * {
     *   "id": "my_hub_format",
     *   "enabled": true,
     *   "header_pattern": "regex (no delimiters) that must appear somewhere in the body",
     *   "row_pattern": "regex (no delimiters) with named groups <tag>, optional <description>, <status>",
     *   "stop_pattern": "optional regex; a matching line ends the row scan",
     *   "default_action": "subscribe|unsubscribe|available",
     *   "status_rules": [ { "pattern": "regex tested against the <status> group", "action": "subscribe|unsubscribe|available" } ]
     * }
     *
     * A grammar missing `header_pattern` or `row_pattern`, disabled, or whose
     * regexes fail to compile is skipped entirely rather than partially
     * applied, so a sysop typo in one definition can never produce a
     * misleading partial match.
     *
     * @param array<string, mixed> $grammar
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>|null
     */
    private function matchConfiguredGrammar(array $grammar, string $body): ?array
    {
        if (empty($grammar['enabled'])) {
            return null;
        }

        $headerPattern = $grammar['header_pattern'] ?? null;
        $rowPattern = $grammar['row_pattern'] ?? null;
        if (!is_string($headerPattern) || $headerPattern === '' || !is_string($rowPattern) || $rowPattern === '') {
            return null;
        }

        $defaultAction = $grammar['default_action'] ?? self::ACTION_AVAILABLE;
        if (!in_array($defaultAction, self::VALID_ACTIONS, true)) {
            $defaultAction = self::ACTION_AVAILABLE;
        }

        $stopPattern = is_string($grammar['stop_pattern'] ?? null) && $grammar['stop_pattern'] !== '' ? $grammar['stop_pattern'] : null;

        $statusRules = [];
        foreach ((array)($grammar['status_rules'] ?? []) as $rule) {
            if (!is_array($rule) || !isset($rule['pattern'], $rule['action']) || !is_string($rule['pattern'])) {
                continue;
            }
            if (!in_array($rule['action'], self::VALID_ACTIONS, true)) {
                continue;
            }
            if (!self::isValidPattern($rule['pattern'])) {
                continue;
            }
            $statusRules[] = $rule;
        }

        if (!self::isValidPattern($headerPattern) || !self::isValidPattern($rowPattern)
            || ($stopPattern !== null && !self::isValidPattern($stopPattern))) {
            $this->logger->warning('AreaFixParser: data-driven grammar has an invalid regex, skipping', [
                'grammar_id' => (string)($grammar['id'] ?? ''),
            ]);
            return null;
        }

        if (!preg_match('/' . $headerPattern . '/im', $body)) {
            return null;
        }

        $lines = explode("\n", $body);
        $areas = [];

        foreach ($lines as $line) {
            $trimmed = trim($line);
            if ($trimmed === '') {
                if (!empty($areas)) {
                    break;
                }
                continue;
            }

            if ($stopPattern !== null && preg_match('/' . $stopPattern . '/i', $trimmed)) {
                break;
            }

            if (preg_match('/' . $rowPattern . '/', $line, $m) !== 1) {
                continue;
            }

            $tag = strtoupper(trim($m['tag'] ?? ''));
            if ($tag === '' || !self::isValidTag($tag)) {
                continue;
            }

            $desc = isset($m['description']) ? trim($m['description']) : '';
            $statusText = isset($m['status']) ? trim($m['status']) : '';

            $action = $defaultAction;
            foreach ($statusRules as $rule) {
                if (preg_match('/' . $rule['pattern'] . '/i', $statusText)) {
                    $action = $rule['action'];
                    break;
                }
            }

            $areas[] = [
                'name'          => $tag,
                'description'   => $desc !== '' ? $desc : null,
                'action'        => $action,
                'is_subscribed' => $action === self::ACTION_SUBSCRIBE,
            ];
        }

        return $areas;
    }

    /**
     * Check whether a user-supplied regex fragment (no delimiters) compiles
     * without throwing a PHP warning, so an invalid pattern in a sysop-edited
     * (or AI-generated) grammar definition is skipped rather than crashing
     * the parser. Public so callers validating a grammar before it's ever
     * written to config/areafix_grammars.json (e.g. the AI-assisted grammar
     * generator route) can reuse the exact same check.
     */
    public static function isValidPattern(string $pattern): bool
    {
        return @preg_match('/' . $pattern . '/i', '') !== false;
    }

    /**
     * Validate whether a string is syntactically a valid FTN echoarea/filearea tag.
     */
    public static function isValidTag(string $tag): bool
    {
        $upper = strtoupper(trim($tag));
        $len = strlen($upper);

        if ($len < 2 || $len > 60) {
            return false;
        }

        // Permitted characters: letters, digits, underscore, hyphen, period
        if (!preg_match('/^[A-Z0-9_\-\.]+$/', $upper)) {
            return false;
        }

        // Must contain at least one letter (prevents pure numbers or punctuation)
        if (!preg_match('/[A-Z]/', $upper)) {
            return false;
        }

        // Must not be a structural table token or command keyword
        $reserved = [
            'AREA', 'ECHOTAG', 'TAG', 'DESCRIPTION', 'DESC',
            'STATUS', 'MSGS', 'FILES', 'COMMAND', 'RESULT',
            'HELP', 'PASSWORD', 'ORIGIN', 'DEST'
        ];

        return !in_array($upper, $reserved, true);
    }

    /**
     * Deduplicate parsed areas by uppercase tag, giving precedence to subscriptions
     * and non-empty descriptions.
     *
     * @param array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}> $areas
     * @return array<int, array{name: string, description: ?string, action: string, is_subscribed: bool}>
     */
    private function deduplicateAreas(array $areas): array
    {
        $map = [];

        foreach ($areas as $item) {
            $tag = strtoupper($item['name']);
            if (!isset($map[$tag])) {
                $map[$tag] = $item;
                continue;
            }

            // Precedence: subscribe > unsubscribe > available
            if ($item['action'] === self::ACTION_SUBSCRIBE) {
                $map[$tag]['action'] = self::ACTION_SUBSCRIBE;
                $map[$tag]['is_subscribed'] = true;
            } elseif ($item['action'] === self::ACTION_UNSUBSCRIBE && $map[$tag]['action'] !== self::ACTION_SUBSCRIBE) {
                $map[$tag]['action'] = self::ACTION_UNSUBSCRIBE;
                $map[$tag]['is_subscribed'] = false;
            }

            // Retain description if provided
            if (!empty($item['description']) && empty($map[$tag]['description'])) {
                $map[$tag]['description'] = $item['description'];
            }
        }

        return array_values($map);
    }
}
